### ISSUE TITLE
Problems with Docker building?

### ISSUE THREAD

**Issue by daniel-jettka** [Edirom/MerMEId#108]
mentioned by @riedde 
locally built MerMEId image but did not work

**Comment by peterstadler** [comment]
Just tested with current develop branch and it works for me like: 
```shell
docker build -t mermeid .
docker run --rm -p8080:8080 mermeid
```

Could that be an arm64 issue (because our `existdb/existdb` base image is only available for amd64)?

But anyway, a more detailed error description would be much appreciated!

**Comment by daniel-jettka** [comment]
@riedde Could you check and give some more info? Thanks! :-)

**Comment by riedde** [comment]
@peterstadler Yes, it is an amd64 issue. I didn't notice that `existdb/existdb` is used. I always use `peterstadler/existdb` and that image also works on Macs with Apple Silicon.

Here the report when starting the container:
```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8   -Dsun.jnu.encoding=UTF-8   -Djava.awt.headless=true   -Dorg.exist.db-connection.cacheSize=256M   -Dorg.exist.db-connection.pool.max=20   -Dlog4j.configurationFile=/exist/etc/log4j2.xml   -Dexist.home=/exist   -Dexist.configurationFile=/exist/etc/conf.xml   -Djetty.home=/exist   -Dexist.jetty.config=/exist/etc/jetty/standard.enabled-jetty-configs   -XX:+UnlockExperimentalVMOptions   -XX:+UseCGroupMemoryLimitForHeap   -XX:+UseG1GC   -XX:+UseStringDeduplication   -XX:MaxRAMFraction=1   -XX:+ExitOnOutOfMemoryError
OpenJDK 64-Bit Server VM warning: Unable to open cgroup memory limit file /sys/fs/cgroup/memory/memory.limit_in_bytes (No such file or directory)
2022-05-20 07:48:46,175 [main] INFO  (JettyStart.java [run]:181) - Running with Java 1.8.0_322 [Oracle Corporation (OpenJDK 64-Bit Server VM) in /usr/lib/jvm/java-8-openjdk-amd64/jre] 
2022-05-20 07:48:46,183 [main] INFO  (JettyStart.java [run]:188) - Approximate maximum amount of memory for JVM: 4 GB 
2022-05-20 07:48:46,184 [main] INFO  (JettyStart.java [run]:189) - Number of processors available to JVM: 5 
2022-05-20 07:48:46,184 [main] INFO  (JettyStart.java [run]:191) - Running as user 'root' 
2022-05-20 07:48:46,185 [main] INFO  (JettyStart.java [run]:192) - [eXist Home : /exist] 
2022-05-20 07:48:46,190 [main] INFO  (JettyStart.java [run]:193) - [eXist Version : 6.0.1] 
2022-05-20 07:48:46,191 [main] INFO  (JettyStart.java [run]:194) - [eXist Build : 20220209234135] 
2022-05-20 07:48:46,192 [main] INFO  (JettyStart.java [run]:195) - [Git commit : 51506fc97a9e5bb55fdea71fc76def2c9d402886] 
2022-05-20 07:48:46,193 [main] INFO  (JettyStart.java [run]:197) - [Operating System : Linux 5.10.104-linuxkit amd64] 
2022-05-20 07:48:46,194 [main] INFO  (JettyStart.java [run]:198) - [log4j.configurationFile : /exist/etc/log4j2.xml] 
2022-05-20 07:48:46,298 [main] INFO  (JettyStart.java [run]:199) - [jetty Version: 9.4.44.v20210927] 
2022-05-20 07:48:46,299 [main] INFO  (JettyStart.java [run]:200) - [jetty.home : /exist] 
2022-05-20 07:48:46,299 [main] INFO  (JettyStart.java [run]:201) - [jetty.base : /exist] 
2022-05-20 07:48:46,300 [main] INFO  (JettyStart.java [run]:202) - [jetty configuration : /exist/etc/jetty/standard.enabled-jetty-configs] 
2022-05-20 07:48:47,253 [main] INFO  (JettyStart.java [run]:211) - Configuring eXist from /exist/etc/conf.xml 
2022-05-20 07:48:48,367 [main] INFO  (ExistRepository.java [prepare]:89) - Using directory /exist/etc/../data/expathrepo for expath package repository 
2022-05-20 07:48:52,412 [main] INFO  (AutoDeploymentTrigger.java [execute]:95) - Scanning autodeploy directory. Found 10 app packages. 
2022-05-20 07:48:52,938 [main] INFO  (Deployment.java [installAndDeploy]:192) - Application package http://exist-db.org/apps/dashboard already installed. Skipping. 
2022-05-20 07:48:52,975 [main] INFO  (Deployment.java [installAndDeploy]:192) - Application package http://exist-db.org/apps/eXide already installed. Skipping. 
2022-05-20 07:48:53,095 [main] INFO  (Deployment.java [installAndDeploy]:192) - Application package http://exist-db.org/apps/doc already installed. Skipping. 
2022-05-20 07:48:53,116 [main] INFO  (Deployment.java [installAndDeploy]:192) - Application package http://exist-db.org/apps/fundocs already installed. Skipping. 
2022-05-20 07:48:53,124 [main] INFO  (Deployment.java [installAndDeploy]:192) - Application package http://www.functx.com already installed. Skipping. 
2022-05-20 07:48:53,151 [main] INFO  (Deployment.java [installAndDeploy]:220) - Package https://github.com/edirom/mermeid depends on http://exist-db.org/apps/shared 
2022-05-20 07:48:53,152 [main] ERROR (AutoDeploymentTrigger.java [execute]:127) - Exception during deployment of app mermeid-2.0.0-alpha.5-24-g43eb2d6b.xar: Missing dependency: package http://exist-db.org/apps/shared could not be resolved. 
org.expath.pkg.repo.PackageException: Missing dependency: package http://exist-db.org/apps/shared could not be resolved.
	at org.exist.repo.Deployment.installAndDeploy(Deployment.java:256) ~[exist.uber.jar:6.0.1]
	at org.exist.repo.AutoDeploymentTrigger.execute(AutoDeploymentTrigger.java:125) [exist.uber.jar:6.0.1]
	at org.exist.storage.StartupTriggersManager.startPreMultiUserSystem(StartupTriggersManager.java:61) [exist.uber.jar:6.0.1]
	at org.exist.storage.BrokerPoolServicesManager.startPreMultiUserSystemServices(BrokerPoolServicesManager.java:264) [exist.uber.jar:6.0.1]
	at org.exist.storage.BrokerPool._initialize(BrokerPool.java:683) [exist.uber.jar:6.0.1]
	at org.exist.storage.BrokerPool.initialize(BrokerPool.java:451) [exist.uber.jar:6.0.1]
	at org.exist.storage.BrokerPools.configure(BrokerPools.java:177) [exist.uber.jar:6.0.1]
	at org.exist.storage.BrokerPools.configure(BrokerPools.java:112) [exist.uber.jar:6.0.1]
	at org.exist.jetty.JettyStart.run(JettyStart.java:216) [exist.uber.jar:6.0.1]
	at org.exist.jetty.JettyStart.main(JettyStart.java:103) [exist.uber.jar:6.0.1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_322]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_322]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_322]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_322]
	at org.exist.start.Main.invokeMain(Main.java:153) [exist.uber.jar:6.0.1]
	at org.exist.start.Main.runEx(Main.java:292) [exist.uber.jar:6.0.1]
	at org.exist.start.Main.run(Main.java:158) [exist.uber.jar:6.0.1]
	at org.exist.start.Main.main(Main.java:95) [exist.uber.jar:6.0.1]
2022-05-20 07:48:53,286 [main] INFO  (Deployment.java [installAndDeploy]:192) - Application package http://exist-db.org/apps/monex already installed. Skipping. 
2022-05-20 07:48:53,297 [main] INFO  (Deployment.java [installAndDeploy]:192) - Application package http://exist-db.org/apps/existdb-packageservice already installed. Skipping. 
2022-05-20 07:48:53,315 [main] INFO  (Deployment.java [installAndDeploy]:192) - Application package http://exist-db.org/xquery/semver-xq already installed. Skipping. 
2022-05-20 07:48:53,321 [main] INFO  (Deployment.java [installAndDeploy]:192) - Application package http://exist-db.org/html-templating already installed. Skipping. 
2022-05-20 07:48:53,425 [main] INFO  (JettyStart.java [run]:235) - [loading jetty configuration : /exist/etc/jetty/jetty-bytebufferpool.xml] 
2022-05-20 07:48:53,737 [main] INFO  (JettyStart.java [run]:235) - [loading jetty configuration : /exist/etc/jetty/jetty-threadpool.xml] 
2022-05-20 07:48:53,816 [main] INFO  (JettyStart.java [run]:235) - [loading jetty configuration : /exist/etc/jetty/jetty.xml] 
2022-05-20 07:48:54,012 [main] INFO  (JettyStart.java [run]:235) - [loading jetty configuration : /exist/etc/jetty/jetty-gzip.xml] 
2022-05-20 07:48:54,146 [main] INFO  (JettyStart.java [run]:235) - [loading jetty configuration : /exist/etc/jetty/jetty-http.xml] 
2022-05-20 07:48:54,278 [main] INFO  (JettyStart.java [run]:235) - [loading jetty configuration : /exist/etc/jetty/jetty-jaas.xml] 
2022-05-20 07:48:54,322 [main] INFO  (JettyStart.java [run]:235) - [loading jetty configuration : /exist/etc/jetty/jetty-jmx.xml] 
2022-05-20 07:48:54,997 [main] INFO  (JettyStart.java [run]:235) - [loading jetty configuration : /exist/etc/jetty/jetty-requestlog.xml] 
2022-05-20 07:48:55,400 [main] INFO  (JettyStart.java [run]:235) - [loading jetty configuration : /exist/etc/jetty/jetty-ssl.xml] 
2022-05-20 07:48:55,486 [main] INFO  (JettyStart.java [run]:235) - [loading jetty configuration : /exist/etc/jetty/jetty-ssl-context.xml] 
2022-05-20 07:48:55,597 [main] INFO  (JettyStart.java [run]:235) - [loading jetty configuration : /exist/etc/jetty/jetty-https.xml] 
2022-05-20 07:48:55,640 [main] INFO  (JettyStart.java [run]:235) - [loading jetty configuration : /exist/etc/jetty/jetty-deploy.xml] 
2022-05-20 07:48:55,719 [main] INFO  (JettyStart.java [run]:235) - [loading jetty configuration : /exist/etc/jetty/jetty-annotations.xml] 
2022-05-20 07:48:55,824 [main] DEBUG (JettyStart.java [startJetty]:464) - BrokerPoolsAndJetty.ShutdownHook hook registered 
2022-05-20 07:48:55,825 [main] INFO  (JettyStart.java [startJetty]:477) - [Starting jetty component : org.eclipse.jetty.server.Server] 
2022-05-20 07:48:55,826 [main] INFO  (JettyStart.java [lifeCycleStarting]:634) - Jetty server starting... 
2022-05-20 07:48:59,126 [main] INFO  (JettyStart.java [shutdown]:571) - Database shutdown: stopping server in 1sec ... 
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.invokeMethod(XmlConfiguration.java:765)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.invokeMethod(XmlConfiguration.java:760)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.call(XmlConfiguration.java:979)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.call(XmlConfiguration.java:942)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:515)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.newObj(XmlConfiguration.java:1022)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.itemValue(XmlConfiguration.java:1540)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.value(XmlConfiguration.java:1441)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.set(XmlConfiguration.java:571)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:509)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.get(XmlConfiguration.java:886)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:518)
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:468)
	at org.eclipse.jetty.xml.XmlConfiguration.configure(XmlConfiguration.java:380)
	at org.eclipse.jetty.deploy.providers.WebAppProvider.createContextHandler(WebAppProvider.java:300)
	at org.eclipse.jetty.deploy.App.getContextHandler(App.java:99)
	at org.eclipse.jetty.deploy.bindings.StandardDeployer.processBinding(StandardDeployer.java:39)
	at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:188)
	at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:517)
	at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:157)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:173)
	at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:448)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:66)
	at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:785)
	at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:754)
	at org.eclipse.jetty.util.Scanner.scan(Scanner.java:641)
	at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:540)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:146)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:605)
	at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:252)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.server.Server.start(Server.java:423)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.server.Server.doStart(Server.java:387)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.exist.jetty.JettyStart.startJetty(JettyStart.java:478)
	at org.exist.jetty.JettyStart.run(JettyStart.java:248)
	at org.exist.jetty.JettyStart.main(JettyStart.java:103)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.exist.start.Main.invokeMain(Main.java:153)
	at org.exist.start.Main.runEx(Main.java:292)
	at org.exist.start.Main.run(Main.java:158)
	at org.exist.start.Main.main(Main.java:95)
Caused by: java.lang.RuntimeException: java.io.IOException: Function not implemented
	at org.eclipse.jetty.util.component.ContainerLifeCycle.addBean(ContainerLifeCycle.java:408)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.addBean(ContainerLifeCycle.java:313)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.updateBean(ContainerLifeCycle.java:864)
	at org.eclipse.jetty.security.HashLoginService.setUserStore(HashLoginService.java:126)
	at org.eclipse.jetty.security.HashLoginService.doStart(HashLoginService.java:176)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	... 54 more
Caused by: java.io.IOException: Function not implemented
	at sun.nio.fs.LinuxWatchService.<init>(LinuxWatchService.java:64)
	at sun.nio.fs.LinuxFileSystem.newWatchService(LinuxFileSystem.java:47)
	at org.eclipse.jetty.util.PathWatcher.doStart(PathWatcher.java:872)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.security.PropertyUserStore.doStart(PropertyUserStore.java:315)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.addBean(ContainerLifeCycle.java:384)
	... 59 more
2022-05-20 07:48:59,197 [global.BrokerPoolsAndJetty.ShutdownHook] INFO  (JettyStart.java [lifeCycleStopping]:656) - Jetty server stopping... 
2022-05-20 07:48:59,218 [global.BrokerPoolsAndJetty.ShutdownHook] INFO  (JettyStart.java [lifeCycleStopped]:663) - Jetty server stopped 
```

**Comment by peterstadler** [comment]
So, there's a linux/arm64 image for MerMEId available now from e.g. https://hub.docker.com/repository/docker/edirom/mermeid/tags

This image is based on `duncdrum/existdb` which seems closest to the `existdb/existdb` image we used before. Please give it a try and report back whether it works for you!

**Comment by riedde** [comment]
Thank you very much. Now it (`edirom/mermeid:develop`) starts without errors and it is running. I didn't configure users before so I couldn't test too much, but Everything looked like I expected it. Also the behaviour.

**Comment by peterstadler** [comment]
I take @riedde 's report as approval and close the issue :)

**Comment by DILewis** [comment]
Current version failed to build on Apple Silicon, because it couldn't pull the arm64 version of existdb. Changing from 6.0.1 to 6.3 in the Dockerfile worked.

**Comment by peterstadler** [comment]
For the record: the current state of eXistdb Docker images is a bit messed up. I asked on the eXist slack:
> I'm aware of existdb/existdb  but the 6.3.0  tag there has no arm support. There's also 6.3.0-SNAPSHOT which has support for amd and arm – but what does snapshot mean and what's the difference to 6.3.0 ?
For arm support there was some recommendation to use duncdrum/existdb – but that does not feature a 6.3.0  tag.

The answer was more or less to wait for eXist v6.3.1 which will be released as multi-arch images soon.
