### ISSUE TITLE
post-install script throws an error when setting admin password

### ISSUE THREAD

**Issue by peterstadler** [Edirom/MerMEId#120]
This affects the Docker image where we suggest to users to mount the data volume into the container for persistence. Yet, when starting such a system for the first time – and trying to provide an admin password as environment variable – an error is thrown:

```txt
2022-10-17 12:36:39,179 [main] ERROR (AutoDeploymentTrigger.java [execute]:127) - Exception during deployment of app mermeid-2.0.0-alpha.6-14-ga7c74611.xar: Error found while processing repo.xml: exerr:ERROR org.exist.EXistException: Database instance 'exist' is not available [at line 39, column 50]
In function:
	local:set-admin-password() [149:9:/exist/etc/../data/expathrepo/mermeid-2.0.0-alpha.6-14-ga7c74611/post-install.xql] 
org.expath.pkg.repo.PackageException: Error found while processing repo.xml: exerr:ERROR org.exist.EXistException: Database instance 'exist' is not available [at line 39, column 50]
In function:
	local:set-admin-password() [149:9:/exist/etc/../data/expathrepo/mermeid-2.0.0-alpha.6-14-ga7c74611/post-install.xql]
	at org.exist.repo.Deployment.deploy(Deployment.java:469) ~[exist-core-6.0.1.jar:6.0.1]
	at org.exist.repo.Deployment.installAndDeploy(Deployment.java:281) ~[exist-core-6.0.1.jar:6.0.1]
	at org.exist.repo.AutoDeploymentTrigger.execute(AutoDeploymentTrigger.java:125) [exist-core-6.0.1.jar:6.0.1]
	at org.exist.storage.StartupTriggersManager.startPreMultiUserSystem(StartupTriggersManager.java:61) [exist-core-6.0.1.jar:6.0.1]
	at org.exist.storage.BrokerPoolServicesManager.startPreMultiUserSystemServices(BrokerPoolServicesManager.java:264) [exist-core-6.0.1.jar:6.0.1]
	at org.exist.storage.BrokerPool._initialize(BrokerPool.java:683) [exist-core-6.0.1.jar:6.0.1]
	at org.exist.storage.BrokerPool.initialize(BrokerPool.java:451) [exist-core-6.0.1.jar:6.0.1]
	at org.exist.storage.BrokerPools.configure(BrokerPools.java:177) [exist-core-6.0.1.jar:6.0.1]
	at org.exist.storage.BrokerPools.configure(BrokerPools.java:112) [exist-core-6.0.1.jar:6.0.1]
	at org.exist.jetty.JettyStart.run(JettyStart.java:216) [exist-core-6.0.1.jar:6.0.1]
	at org.exist.jetty.JettyStart.main(JettyStart.java:103) [exist-core-6.0.1.jar:6.0.1]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.exist.start.Main.invokeMain(Main.java:153) [exist-start-6.0.1.jar:6.0.1]
	at org.exist.start.Main.runEx(Main.java:292) [exist-start-6.0.1.jar:6.0.1]
	at org.exist.start.Main.run(Main.java:158) [exist-start-6.0.1.jar:6.0.1]
	at org.exist.start.Main.main(Main.java:95) [exist-start-6.0.1.jar:6.0.1]
```

The tested command was: 

```
docker run --rm -v `pwd`/exist:/exist/data -e MERMEID_admin_password=foobar -p8080:8080  edirom/mermeid:develop
```

**Comment by peterstadler** [comment]
At first I thought that would only appear with mounted data volumes but I can reproduce this even without mounted volumes. NB: setting the password works (you are able to log in with the new password)!

**Comment by peterstadler** [comment]
@AnastasiaWawilow and I had a look at it today and we can confirm that this error appears
* on both images tags  "develop" and "develop-java11-ShenGC"
* for both architectures "arm64" and "amd64" 
* for both env variables "MERMEID_admin_password" and "MERMEID_admin_password_file"
